# Generated by Django 3.0.7 on 2020-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('fav_dish', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
