# Generated by Django 3.0.7 on 2020-07-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20200706_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecords',
            new_name='AccessRecord',
        ),
    ]
