# Generated by Django 3.0.7 on 2020-07-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
