# Generated by Django 3.0.7 on 2020-07-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_auto_20200711_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='task',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
